default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: hire_sprint_development
  username: postgres
  password: postgres
  host:     localhost
  port:     5432

test:
  <<: *default
  database: hire_sprint_test
  username: postgres
  password: postgres
  host:     localhost
  port:     5432

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
